/* CSCI3731 (C++) Programming Assignment Week 4
April 5, 2018
Rian Blahut
*/

/*
Write a program that uses a random number generator to generate a two digit
positive integer and allows the user to perform one or more of the following
operations:
1. Double the number
2. Reverse the digits of the number
3. Raise the number to the power of 3
4. Sum the digits of the number
5. If the number is a two digit number, then raise the first digit to the power
of the second digit
6. If the number is a three digit number and the last digit is less tha or equal
to 4, then raise the first two digits to the power of the last digit.
Each successive operation should be performed on the numer generated by the last
operation. Your program should not contain any global variables and each of the
these operations must be implement by a separate function.  Your program should
be menu driven.  */

#include <iostream>
#include <stdio.h>
#include <cstdlib>
#include <time.h>
#include <string>
#include <math.h>

using namespace std;

// Function Declarations
int generateRandom(); //Generates a random two-digit integer (first para)
void displayMenu(int n); //Repeatedly displays the menu (mentioned in last para.)
int doubleNum(int n); //Doubles the number (part 1)
int reverseNum(int n); //Reverses digits of the number (part 2)
int raiseToThree(int n); //Raises number to third power (part 3)
int sumDigits(int n); //Sums the digitss (part 4)
int firstToSecond(int n); //Takes first digit to second digit's power (part 5)
int firstTwotoThird(int n); //Takes first two digits to third's power (part 6)

int main() {

  //Random number generator is seeded, and the initial number is created
  srand (time(NULL));
  int number = generateRandom();
  int choice = 0;

  //Main portion. Unless the user exits (incorrect choice), the program continues
  while (choice >= 0 && choice < 7) {
    displayMenu(number);
    cin >> choice;

    //List of choices corresponding to functions
    if (choice == 1) number = doubleNum(number);
    else if (choice == 2) number = reverseNum(number);
    else if (choice == 3) number = raiseToThree(number);
    else if (choice == 4) number = sumDigits(number);
    else if (choice == 5) number = firstToSecond(number);
    else if (choice == 6) number = firstTwotoThird(number);
    else break;
  }

  return 0;
}

// Function Definitions

int generateRandom() {
  return rand() % 90 + 10; //Output will be two digits (10-99)
}
void displayMenu(int n) {
  cout << "\nCurrent number: " << n << endl << endl;
  cout << "---Menu--- \n1. Double the number \n2. Reverse the number"
  << "\n3. Raise to third power \n4. Sum the digits \n5. Take first digit "
  << "to second digit \n6. Take first two digits to third \n7. Exit program" << endl;
  cout << "Enter selection: ";
}
int doubleNum(int n) {
  cout << "*DOUBLING NUMBER*" << endl;
  return n *= 2;
}
int reverseNum(int n) {
  cout << "*REVERSING NUMBER*" << endl;
  int i = n;
  int o = 0;
  while (i != 0) {
    o *= 10;
    o += i % 10;
    i /= 10;
  }
  return o;
}
int raiseToThree(int n) {
  cout << "*RAISING TO THIRD*" << endl;
  return n*n*n;
}
int sumDigits(int n) {
  //Number is converted to string, then individual digits are converted back to
  //ints while an accumulator keeps track of the running total
  cout << "*SUMMING DIGITS*" << endl;
  string numString = to_string(n);
  int result = 0;
  for (unsigned int i = 0; i < numString.length(); i++) {
    int numFromString = numString[i] - '0';
    result += numFromString;
  }
  return result;
}
int firstToSecond(int n) {
  int result = n;
  if (n < 10 || n > 99) { //checks to see if valid
    cout << "*NUMBER NOT TWO DIGITS*" << endl;
  }
  else { //determines first and second digits
    cout << "*EMPOWERING DIGITS*" << endl;
    int second = n % 10;
    int first = (n - second) / 10;
    double doubleNum = pow(first, second); //pow function for exponent
    result = doubleNum; //converts double back to int for output
  }
  return result;
}
int firstTwotoThird(int n) {
  int result = n;
  if (n < 100 || n > 999) { //checks to see if valid
    cout << "*NUMBER NOT THREE DIGITS*" << endl;
  }
  else if (n % 10 > 4) {
    cout << "*THIRD DIGIT TOO HIGH*" << endl;
  }
  else { //determines last digit, then first two
    cout << "*EMPOWERING DIGITS*" << endl;
    int third = n % 10;
    int firstTwo = (n - third) / 10;
    double doubleNum = pow(firstTwo, third); //takes power
    result = doubleNum; //converts double back to int
  }
  return result;
}

/* Assignment comments
1. This program works with the possible exception of an easy to encounter integer
overflow on part 6. This might be solved by converting everything to a long but
I think that would break a lot of the other functions.
2. My approach was to make functions for all the math operations, plus displaying
a menu (since it appears every loop) and generating the number. Each function uses
a slightly different approach.
3. Since the number is randomly generated I just spent some time workign the number
with the written functions (i.e. getting the third digit to be >4 to trigger the
else-if in part 6).
4. I learned how the random number generator works (and seeding it). Difficulties
included the conversion of ints to strings and back again but I got it sorted out.
5. I consulted a number of websites including mainly cplusplus.com for help on new
functions, stack overflow to troubleshoot some errors I was seeing, and http://cpp.sh
as my actual compiler.
6. I had a real tough time with the programming exercises this week. I got the
first one to work fine but it didn't pass cengage's tests. On the second one I
got totally lost with all the inheritance and how the dependencies work.
*/
